FROM alpine:3.6 as builder

RUN apk add --no-cache git  build-base linux-headers


COPY . /udp2raw-tunnel
WORKDIR /udp2raw-tunnel
RUN make dynamic

FROM alpine:3.6
RUN apk add --no-cache libstdc++ iptables
COPY --from=builder /udp2raw-tunnel/udp2raw_dynamic /bin/
ENTRYPOINT [ "/bin/udp2raw_dynamic" ]
